version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    target-branch: develop

    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/London

    labels:
      - dependencies
      - dotnet