version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    target-branch: develop

    exclude-paths:
      - "src/Dfe.SignIn.AppHost/**"
      - "tests/**"
      
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/London

    labels:
      - dependencies
      - dotnet