apiRules:
  - exclude:
    uidRegex: .*\.Internal\..*
    type: Namespace

  - exclude:
    uidRegex: .*\.Internal\..*
    type: Type

  - exclude:
    hasAttribute:
      uid: System.ObsoleteAttribute
