name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)

trigger: none

resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: feature/DSI-7357

  # containers:
  #   - container: images
  #     type: ACR
  #     azureSubscription: $(devServiceConnection)
  #     resourceGroup: $(platformGlobalIdentifier)$(tranShaCode)-cr
  #     registry: $(platformGlobalIdentifier)$(tranShaCode)signinshdcr
  #     repository: select-organisation
  #     trigger:
  #       tags:
  #         include:
  #           - 'development-*'
  #           - 'release-*'

parameters:
  - name: imageName
    type: string
    displayName: Image name

  - name: containerRegistry
    type: string
    displayName: Container registry
    default: D03
    values:
      - Standard
      - D03

  - name: shaUse
    type: boolean
    displayName: "Use self host agent"
    default: true
  - name: slotDeploy
    type: boolean
    displayName: "Slot deployment"
    default: true
  - name: InfrDeploy
    type: boolean
    displayName: "Deploy infrastrucure only"
    default: false
  - name: gitCheck
    type: boolean
    displayName: "Bypass git check"
    default: false

  - name: location
    type: object
    displayName: "Deployment locations (- westeurope & - northeurope)"
    default:
      - westeurope
      - northeurope

# steps:
  # - script: |
  #     echo "Pretending to deploy..."
  #   displayName: 'Pretend to deploy'

  # - script: |
  #     echo "Pipeline Name: $(Build.DefinitionName)_$(Build.SourceBranchName)_$(Build.BuildId)"
  #     echo "Image Name: $(resources.containers.images.repository)"
  #     echo "Image Tag: $(resources.containers.images.tag)"
  #     echo "Registry: $(resources.containers.images.registry)"
  #   displayName: 'Output Image Details'

variables:
  - group: dsi-global
  - group: dsi-envs-list

  - name: applicationShortName
    value: "sltOrg"
  - name: applicationFullName
    value: "select-organisation"

  - name: lifecycle
    ${{ if contains(parameters.imageName, 'release-') }}:
      value: "Release"
    ${{ else }}:
      value: "Development"

  - name: tran
    value: ${{ eq(parameters.containerRegistry, 'D03') }}
  - name: dev
    value: ${{ and(eq(parameters.containerRegistry, 'Standard'), eq(variables.lifecycle, 'Development')) }}
  - name: test
    value: ${{ and(eq(parameters.containerRegistry, 'Standard'), eq(variables.lifecycle, 'Development')) }}
  - name: pp
    value: ${{ and(eq(parameters.containerRegistry, 'Standard'), eq(variables.lifecycle, 'Release')) }}
  - name: pr
    value: ${{ and(eq(parameters.containerRegistry, 'Standard'), eq(variables.lifecycle, 'Release')) }}

  - name: northeurope
    value: "tran,pp,pr"
  - name: westeurope
    value: "tran,dev,test,pp,pr"

stages:
  - ${{ each location in parameters.location }}:
    - ${{ each env in split(variables[location], ',') }}:
      - ${{ if eq(variables[env], 'true') }}:
        - stage: deployment_${{env}}_${{location}}
          displayName: "Deployment [${{env}}] ${{location}}"
          ${{ if eq(env, 'pr') }}:
            dependsOn: 
              - deployment_pp_westeurope
          variables:
            - name: secRegionId
              value: $(${{ format('{0}{1}', location, 'Id') }})
            - name: environmentId
              value: $[variables['${{env}}EnvId']]
            - name: ServConName
              value: ${{ format('{0}{1}', env, 'ServCon') }}
            - name: ShaCodeName
              value: ${{ format('{0}{1}', env, 'ShaCode') }}
          jobs:
            - template: pipeline/components/deploy/deployAppServicesNodeJs.yml@devopsTemplates
              parameters:
                serviceConnection: $(${{variables.ServConName}})
                shaPool: $[variables['${{env}}ShaPool']]
                shaCode: $(${{variables.ShaCodeName}})
                devOpsEnv: ${{variables.secRegionId}}${{env}}
                environmentName: ${{env}}
                applicationShortName: ${{variables.applicationShortName}}
                applicationFullName: ${{variables.applicationFullName}}
                InfrDeploy: ${{parameters.InfrDeploy}}
                deploymentLocation: ${{location}}
                gitCheck: ${{parameters.gitCheck}}
                tier: presentation
                tierPlan: prestier-g3
                shaUse: ${{parameters.shaUse}}
                slotDeploy: ${{parameters.slotDeploy}}
                appRepoName: ${{variables.applicationFullName}}
                healthCheckEndpoint: v2/healthcheck
                existTag: ${{parameters.imageName}}
                ${{ if eq(parameters.containerRegistry, 'D03') }}:
                  ContRegServerCode: $(tranShaCode)
                ${{ else }}:
                  ContRegServerCode: $(prShaCode)
                skipHealthCheck: true
