name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: feature/DSI-7357

trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - src/*
      - tests/*

parameters:
  - name: buildSelectOrganisation
    type: boolean
    displayName: "Build 'Select Organisation'"
    default: false
  - name: buildPublicApi
    type: boolean
    displayName: "Build 'Public API'"
    default: false
  - name: publishAllPackages
    type: boolean
    displayName: "Publish all packages"
    default: false

  - name: target
    type: string
    displayName: Target
    default: Development
    values:
      - Development
      - Release
  - name: forTranEnvironment
    type: boolean
    displayName: "For TRAN environment"
    default: true

  - name: applications
    type: object
    default:
      - displayName: Select Organisation
        name: select-organisation
        shortName: sltOrg
        projectName: Dfe.SignIn.Web.SelectOrganisation
        triggerVariable: buildSelectOrganisation

      - displayName: Public API
        name: public-api-v2
        shortName: papiV2
        projectName: Dfe.SignIn.PublicApi
        triggerVariable: buildPublicApi

variables:
  - group: dsi-global
  - group: dsi-envs-list

jobs:
  - job: checks
    displayName: Checks
    pool:
      vmImage: windows-latest
    steps:
      - checkout: self
        persistCredentials: true
        path: s/self
      - checkout: devopsTemplates
        path: s/devopsTemplates

      - template: ./templates/selectProjects.yml

      - task: UseDotNet@2
        displayName: Use version 8.x of .NET
        inputs:
          packageType: 'runtime'
          version: '8.x'

      - task: PowerShell@2
        displayName: Start sonar scanner
        inputs:
          targetType: inline
          workingDirectory: $(System.DefaultWorkingDirectory)/self
          script: |
            $branchName = "$(Build.SourceBranch)" -replace 'refs/heads/', ''
            dotnet tool install --global dotnet-sonarscanner
            dotnet sonarscanner begin `
              /o:"dfe-digital" `
              /k:"DFE-Digital_dsi-platform" `
              /d:sonar.host.url="https://sonarcloud.io" `
              /d:sonar.token="$(sonarToken)" `
              /d:sonar.branch.name=$branchName `
              /d:sonar.projectBaseDir="$(System.DefaultWorkingDirectory)/self"
            Write-Host "##vso[task.setvariable variable=sonarScannerStarted]true"

      - task: PowerShell@2
        displayName: Build projects
        inputs:
          targetType: inline
          workingDirectory: $(System.DefaultWorkingDirectory)/self
          script: |
            dotnet build ./build.sln `
              /p:Configuration=Release `
              /p:IsPipeline=true

      - task: PowerShell@2
        displayName: Run unit tests
        inputs:
          targetType: inline
          workingDirectory: $(System.DefaultWorkingDirectory)/self
          script: |
            # dotnet test ./build.sln `
            #   --collect "Code Coverage" `
            #   /p:Configuration=Release
            Write-Host "##vso[task.setvariable variable=unitTestsSucceeded]true"

      - task: PowerShell@2
        displayName: Stop sonar scanner
        condition: eq(variables['sonarScannerStarted'], 'true')
        inputs:
          targetType: inline
          workingDirectory: $(System.DefaultWorkingDirectory)/self
          script: |
            dotnet sonarscanner end `
              /d:sonar.token="$(sonarToken)"

      - task: NuGetCommand@2
        displayName: 'Publish packages'
        condition: |
          and(
            succeeded(), eq(variables['unitTestsSucceeded'], 'true'),
            or(
              eq(variables['publishPackages'], 'True'),
              ${{ parameters.publishAllPackages }}
            )
          )
        inputs:
          command: 'push'
          packagesToPush: '$(System.DefaultWorkingDirectory)/self/src/**/*.nupkg;!$(System.DefaultWorkingDirectory)/self/src/**/*.symbols.nupkg'
          nuGetFeedType: 'internal'
          publishVstsFeed: S141-Dfe-Signin/DfeSignIn-DotNet
          allowPackageConflicts: true


  - ${{ each application in parameters.applications }}:
    - job: buildImages_${{ application.shortName }}
      displayName: Build image for '${{ application.displayName }}'
      dependsOn: checks
      pool:
        vmImage: ubuntu-latest
      steps:
        - checkout: self
          persistCredentials: true
          path: s/self
        - checkout: devopsTemplates
          path: s/devopsTemplates

        - template: ./templates/selectProjects.yml

        - task: PowerShell@2
          displayName: Check needs building
          inputs:
            targetType: inline
            script: |
              if (
                '$(deployProjectNames)' -like '**${{ application.projectName }};**' -or
                '${{ parameters[application.triggerVariable] }}' -eq 'true'
              ) {
                Write-Host "##vso[task.setvariable variable=buildImage]true"
              }

        - task: CopyFiles@2
          displayName: "Copy Docker files"
          condition: and(succeeded(), eq(variables.buildImage, 'true'))
          inputs:
            SourceFolder: $(System.DefaultWorkingDirectory)/devopsTemplates
            Contents: |
              docker/Linux-app-service/**
            TargetFolder: $(System.DefaultWorkingDirectory)/Publish
            CleanTargetFolder: true
        
        - task: CopyFiles@2
          displayName: "Copy Docker files"
          condition: and(succeeded(), eq(variables.buildImage, 'true'))
          inputs:
            SourceFolder: $(System.DefaultWorkingDirectory)/self
            Contents: |
              **
            TargetFolder: $(System.DefaultWorkingDirectory)/Publish
            CleanTargetFolder: false

        # # - ${{ each ContRegServer in parameters.ContRegServers }}:
        # - task: AzureCLI@2
        #   displayName: Build image for '${{ application.displayName }}'
        #   condition: and(succeeded(), eq(variables.buildImage, 'true'))
        #   inputs:
        #     azureSubscription: $(devServiceConnection)
        #     scriptType: pscore
        #     scriptLocation: scriptPath
        #     scriptPath: $(System.DefaultWorkingDirectory)/devopsTemplates/scripts/appServiceBuild.ps1
        #     arguments: >
        #       -regServer "$(platformGlobalIdentifier)$(tranShaCode)$(platformGlobalName)shdcr.azurecr.io"
        #       -appName ${{ application.name }} 
        #       -branch $(Build.SourceBranch)
        #       -buildId $(Build.BuildId)
        #       -dockerFileName "appSvcDotNet"
        #       -dotNetProjName "${{ application.projectName }}"
        #     workingDirectory: $(System.DefaultWorkingDirectory)/Publish

        # - ${{ each ContRegServer in parameters.ContRegServers }}:
        - task: AzureCLI@2
          displayName: Build image for '${{ application.displayName }}'
          condition: and(succeeded(), eq(variables.buildImage, 'true'))
          inputs:
            azureSubscription: $(devServiceConnection)
            scriptType: pscore
            scriptLocation: scriptPath
            scriptPath: $(System.DefaultWorkingDirectory)/self/scripts/pipelines/Build-Image.ps1
            arguments: >
              -regServer "$(platformGlobalIdentifier)$(tranShaCode)$(platformGlobalName)shdcr.azurecr.io"
              -appName "${{ application.name }}"
              -target "${{ parameters.target }}"
              -buildId $(Build.BuildId)
              -dockerFileName "appSvcDotNet"
              -dotNetProjName "${{ application.projectName }}"
            workingDirectory: $(System.DefaultWorkingDirectory)/Publish

        - task: PowerShell@2
          displayName: Finished building image
          name: finished
          condition: and(succeeded(), eq(variables.buildImage, 'true'))
          inputs:
            targetType: inline
            script: |
              Write-Host "##vso[task.setvariable variable=imageBuilt;isOutput=true]true"
              Write-Host "##vso[task.setvariable variable=imageBuildId;isOutput=true]$(Build.BuildId)"
