// <auto-generated />
using System;
using Dfe.SignIn.Gateways.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace migrations.Directories
{
    [DbContext(typeof(DbDirectoriesContext))]
    [Migration("20260803140253_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Dfe.SignIn.Core.Entities.Directories.InvitationCallbackEntity", b =>
                {
                    b.Property<Guid>("InvitationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("invitationId");

                    b.Property<string>("SourceId")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("sourceId");

                    b.Property<string>("CallbackUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("callbackUrl");

                    b.Property<string>("ClientId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("clientId");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("InvitationId", "SourceId")
                        .HasName("PK_InvitationCallback");

                    b.ToTable("invitation_callback", (string)null);
                });

            modelBuilder.Entity("Dfe.SignIn.Core.Entities.Directories.InvitationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("ApproverEmail")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("approverEmail");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("code");

                    b.Property<string>("CodeMetaData")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("codeMetaData");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit")
                        .HasColumnName("completed");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<bool>("Deactivated")
                        .HasColumnType("bit")
                        .HasColumnName("deactivated");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("firstName");

                    b.Property<bool>("IsApprover")
                        .HasColumnType("bit")
                        .HasColumnName("isApprover");

                    b.Property<bool>("IsMigrated")
                        .HasColumnType("bit")
                        .HasColumnName("isMigrated");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("lastName");

                    b.Property<string>("OrganisationName")
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("orgName");

                    b.Property<string>("OriginClientId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("originClientId");

                    b.Property<string>("OriginRedirectUri")
                        .HasMaxLength(1024)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1024)")
                        .HasColumnName("originRedirectUri");

                    b.Property<string>("OverrideBody")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("overrideBody");

                    b.Property<string>("OverrideSubject")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("overrideSubject");

                    b.Property<string>("PreviousPassword")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("previousPassword");

                    b.Property<string>("PreviousSalt")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("previousSalt");

                    b.Property<string>("PreviousUsername")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("previousUsername");

                    b.Property<string>("Reason")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("reason");

                    b.Property<bool>("SelfStarted")
                        .HasColumnType("bit")
                        .HasColumnName("selfStarted");

                    b.Property<Guid?>("Uid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("PK_Invitation");

                    b.ToTable("invitation", (string)null);
                });

            modelBuilder.Entity("Dfe.SignIn.Core.Entities.Directories.PasswordHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)")
                        .HasColumnName("password");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("salt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("PK_user_password_history");

                    b.ToTable("password_history", (string)null);
                });

            modelBuilder.Entity("Dfe.SignIn.Core.Entities.Directories.UserCodeEntity", b =>
                {
                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uid");

                    b.Property<string>("CodeType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasDefaultValue("PasswordReset")
                        .HasColumnName("codeType");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("clientId");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("code");

                    b.Property<string>("ContextData")
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)")
                        .HasColumnName("contextData");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("RedirectUri")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("redirectUri");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("Uid", "CodeType")
                        .HasName("PK__user_cod__E4DCEC89DE598738");

                    b.HasIndex(new[] { "Email" }, "idx_user_code_email");

                    b.ToTable("user_code", (string)null);
                });

            modelBuilder.Entity("Dfe.SignIn.Core.Entities.Directories.UserEntity", b =>
                {
                    b.Property<Guid>("Sub")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sub");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EntraDeferUntil")
                        .HasColumnType("datetime")
                        .HasColumnName("entra_defer_until");

                    b.Property<DateTime?>("EntraLinked")
                        .HasColumnType("datetime")
                        .HasColumnName("entra_linked");

                    b.Property<Guid?>("EntraOid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("entra_oid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("given_name");

                    b.Property<bool>("IsEntra")
                        .HasColumnType("bit")
                        .HasColumnName("is_entra");

                    b.Property<bool>("IsInternalUser")
                        .HasColumnType("bit")
                        .HasColumnName("is_internal_user");

                    b.Property<bool>("IsMigrated")
                        .HasColumnType("bit")
                        .HasColumnName("isMigrated");

                    b.Property<bool>("IsTestUser")
                        .HasColumnType("bit")
                        .HasColumnName("is_test_user");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("job_title");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("last_login");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("family_name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)")
                        .HasColumnName("password");

                    b.Property<bool>("PasswordResetRequired")
                        .HasColumnType("bit")
                        .HasColumnName("password_reset_required");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("PrevLogin")
                        .HasColumnType("datetime")
                        .HasColumnName("prev_login");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("salt");

                    b.Property<short>("Status")
                        .HasColumnType("smallint")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("Sub")
                        .HasName("PK__user__DDDF3AD9CA56D5BF");

                    b.HasIndex(new[] { "EntraOid" }, "IDX__user__entra_oid__unique")
                        .IsUnique()
                        .HasFilter("([entra_oid] IS NOT NULL)");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Dfe.SignIn.Core.Entities.Directories.UserPasswordHistoryEntity", b =>
                {
                    b.Property<Guid>("PasswordHistoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("passwordHistoryId");

                    b.Property<Guid>("UserSub")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("userSub");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("PasswordHistoryId", "UserSub")
                        .HasName("ck_user_password_history");

                    b.ToTable("user_password_history", (string)null);
                });

            modelBuilder.Entity("Dfe.SignIn.Core.Entities.Directories.UserPasswordPolicyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("createdAt");

                    b.Property<short?>("PasswordHistoryLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)3)
                        .HasColumnName("password_history_limit");

                    b.Property<string>("PolicyCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("policyCode");

                    b.Property<Guid>("Uid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id")
                        .HasName("PK_UserPasswordPolicy");

                    b.HasIndex("Uid");

                    b.ToTable("user_password_policy", (string)null);
                });

            modelBuilder.Entity("Dfe.SignIn.Core.Entities.Directories.UserStatusChangeReasonEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<short>("NewStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("new_status");

                    b.Property<short>("OldStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("old_status");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5000)")
                        .HasColumnName("reason");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedAt");

                    b.HasKey("Id", "UserId")
                        .HasName("PK_UserStatusChangeReasons");

                    b.HasIndex("UserId");

                    b.ToTable("user_status_change_reasons", (string)null);
                });

            modelBuilder.Entity("Dfe.SignIn.Core.Entities.Directories.InvitationCallbackEntity", b =>
                {
                    b.HasOne("Dfe.SignIn.Core.Entities.Directories.InvitationEntity", "Invitation")
                        .WithMany("InvitationCallbacks")
                        .HasForeignKey("InvitationId")
                        .IsRequired()
                        .HasConstraintName("FK_InvitationCallback_Invitation");

                    b.Navigation("Invitation");
                });

            modelBuilder.Entity("Dfe.SignIn.Core.Entities.Directories.UserPasswordPolicyEntity", b =>
                {
                    b.HasOne("Dfe.SignIn.Core.Entities.Directories.UserEntity", "UidNavigation")
                        .WithMany("UserPasswordPolicies")
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__user_passwo__uid__72E607DB");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("Dfe.SignIn.Core.Entities.Directories.UserStatusChangeReasonEntity", b =>
                {
                    b.HasOne("Dfe.SignIn.Core.Entities.Directories.UserEntity", "User")
                        .WithMany("UserStatusChangeReasons")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserStatusChangeReasons_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dfe.SignIn.Core.Entities.Directories.InvitationEntity", b =>
                {
                    b.Navigation("InvitationCallbacks");
                });

            modelBuilder.Entity("Dfe.SignIn.Core.Entities.Directories.UserEntity", b =>
                {
                    b.Navigation("UserPasswordPolicies");

                    b.Navigation("UserStatusChangeReasons");
                });
#pragma warning restore 612, 618
        }
    }
}
