name: .NET checks

on:
  push:
    paths:
      - 'src/**'
      - 'tests/**'

jobs:
  select-projects:
    runs-on: ubuntu-latest
    outputs:
      package-projects: ${{ steps.get_package_projects.outputs.package_projects }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Initialize solution for affected projects
        shell: pwsh
        run: ./scripts/actions/Initialize-BuildSolutionForChangedProjects

      - name: Run unit tests
        run: dotnet test ./build.sln
