name: Continous integration

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

  merge_group:
    types: [ checks_requested ]

  workflow_dispatch:
    inputs:
      build_select_organisation:
        description: 'Build "Select Organisation"'
        required: true
        default: false
        type: boolean

      build_public_api:
        description: 'Build "Public API"'
        required: true
        default: false
        type: boolean

      lifecycle:
        description: 'Lifecycle'
        required: true
        default: Development
        type: choice
        options:
          - Development
          - Release

  push:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  determine-checks:
    name: Determine checks
    runs-on: ubuntu-latest
    outputs:
      check_powershell: ${{ steps.determine-checks.outputs.check_powershell }}
      check_dotnet: ${{ steps.determine-checks.outputs.check_dotnet }}
      check_docs_templates: ${{ steps.determine-checks.outputs.check_docs_templates }}
      publish_dotnet_image_names: ${{ steps.select-projects.outputs.project_names }}
      publish_dotnet_packages: ${{ steps.determine-checks.outputs.publish_dotnet_packages }}
      publish_docs: ${{ steps.determine-checks.outputs.publish_docs }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine which checks need to run
        id: determine-checks
        shell: pwsh
        run: |
          $changedFiles = ./scripts/workflows/Discover-ChangedFilesInBranch

          $checkPowershell = $changedFiles.Where({ $_ -match "^scripts/" }, 'First').Count -gt 0
          echo "check_powershell=$checkPowershell" >> $env:GITHUB_OUTPUT

          $checkDotnet = $changedFiles.Where({ $_ -match "^(src|tests)/" }, 'First').Count -gt 0
          echo "check_dotnet=$checkDotnet" >> $env:GITHUB_OUTPUT

          $dotnetPackageProjectNames = @(
            'Dfe.SignIn.Core.Framework'
            'Dfe.SignIn.Core.ExternalModels'
            'Dfe.SignIn.PublicApi.Client'
            'Dfe.SignIn.PublicApi.Client.AspNetCore'
          ) -join '|'
          $publishDotnetPackages = $changedFiles.Where({ $_ -match "^src/($packageProjectNames)/" }, 'First').Count -gt 0
          echo "publish_dotnet_packages=$publishDotnetPackages" >> $env:GITHUB_OUTPUT

          $checkDocsTemplates = $changedFiles.Where({ $_ -match "^docs/templates/" }, 'First').Count -gt 0
          echo "check_docs_templates=$checkDocsTemplates" >> $env:GITHUB_OUTPUT

          $publishDocs = $changedFiles.Where({ $_ -match "^docs/(external|templates)/" }, 'First').Count -gt 0
          echo "publish_docs=$publishDocs" >> $env:GITHUB_OUTPUT

      - name: Select deployable projects
        id: select-projects
        shell: pwsh
        run: |
          if ($env:GITHUB_EVENT_NAME -eq 'workflow_dispatch') {
            $projectNames = @(./scripts/workflows/Select-ProjectNamesFromParameters `
              -SelectOrganisation ${{ github.event.inputs.build_select_organisation }} `
              -PublicApi ${{ github.event.inputs.build_public_api }} `
            )
          }
          else {
            $projectNames = @(./scripts/workflows/Select-ProjectNamesFromChanges)
          }
          $jsonNames = ConvertTo-Json $projectNames -Compress
          Write-Output "Project names: $jsonNames"
          echo "project_names=$jsonNames" >> $env:GITHUB_OUTPUT


  # -------------------------------------------------------------------------------------
  # Run checks, build and then publish any Docker images to the container registry.
  # -------------------------------------------------------------------------------------

  powershell-checks:
    name: Powershell checks
    uses: ./.github/workflows/powershell-checks.yml
    needs: determine-checks
    if: "${{ needs.determine-checks.outputs.check_powershell == 'true' }}"
    # The following permissions are needed by 'dorny/test-reporter'.
    permissions:
      checks: write

  dotnet-checks:
    name: .NET checks
    uses: ./.github/workflows/dotnet-checks.yml
    needs: determine-checks
    if: "${{ needs.determine-checks.outputs.check_dotnet == 'true' }}"
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dotnet-build:
    name: .NET build images
    uses: ./.github/workflows/dotnet-build-image.yml
    needs: determine-checks
    strategy:
      matrix:
        project_name: ${{ fromJson(needs.determine-checks.outputs.publish_dotnet_image_names) }}
    with:
      project_name: ${{ matrix.project_name }}
      implied_lifecycle: ${{ github.ref == 'refs/head/main' && 'rel' || 'dev' }}
      override_lifecycle: ${{ github.event.inputs.lifecycle || '' }}

  dotnet-packages:
    name: .NET publish packages
    uses: ./.github/workflows/dotnet-packages.yml
    needs: determine-checks
    if: "${{ needs.determine-checks.outputs.publish_dotnet_packages == 'true' }}"

  docs-templates-checks:
    name: Docs templates checks
    uses: ./.github/workflows/docs-templates-checks.yml
    needs: determine-checks
    if: "${{ needs.determine-checks.outputs.check_docs_templates == 'true' }}"

  docs-build:
    name: Build documentation
    uses: ./.github/workflows/docs-build.yml
    needs: determine-checks
    if: "${{ needs.determine-checks.outputs.publish_docs == 'true' }}"


  # -------------------------------------------------------------------------------------
  # Publish any packages and trigger any CD pipelines.
  # -------------------------------------------------------------------------------------

  wait-trigger-cd:
    name: Wait to trigger
    runs-on: ubuntu-latest
    needs:
      - determine-checks
      - powershell-checks
      - dotnet-checks
      - dotnet-build
      - dotnet-packages
      - docs-templates-checks
      - docs-build
    if: ${{ always() && !failure() }}
    steps:
      - name: Triggering deployments
        shell: pwsh
        run: Write-Host Triggering deployments...

  dotnet-trigger-cd:
    name: .NET deploy
    uses: ./.github/workflows/dotnet-deploy-image.yml
    needs:
      - determine-checks
      - wait-trigger-cd
    if: ${{ always() && !failure() }}
    strategy:
      matrix:
        project_name: ${{ fromJson(needs.determine-checks.outputs.publish_dotnet_image_names) }}
    with:
      project_name: ${{ matrix.project_name }}
      implied_lifecycle: ${{ github.ref == 'refs/head/main' && 'rel' || 'dev' }}
      override_lifecycle: ${{ github.event.inputs.lifecycle || '' }}

  docs-trigger-cd:
    name: Docs deploy
    uses: ./.github/workflows/docs-deploy.yml
    needs: wait-trigger-cd
    if: "${{ always() && !failure() && needs.determine-checks.outputs.check_docs_templates == 'true' }}"
