name: CI

run-name: ${{ github.event.pull_request.title || github.event.merge_group.head_commit.message }}

on:
  pull_request:
    types: [opened, reopened, synchronize]

  merge_group:
    types: [checks_requested]

  workflow_dispatch:
    inputs:
      check_powershell:
        description: Run PowerShell checks
        default: false
        type: boolean

      check_dotnet:
        description: Run .NET checks
        default: false
        type: boolean

      check_docs:
        description: Run external docs checks
        default: false
        type: boolean

      publish_dotnet_packages:
        description: Publish .NET packages
        default: false
        type: boolean

      build_for_repository:
        description: Build for repository
        default: (n/a)
        type: choice
        options:
          - (n/a)
          - auth-extensions
          - developer
          - frontend
          - help
          - internal-api
          - public-api
          - select-organisation
          - (all components)

      lifecycle:
        description: Lifecycle
        required: true
        default: Development
        type: choice
        options:
          - Development
          - Release

      transformation_environment:
        description: For transformation environment
        default: false
        type: boolean

  #push: # Useful for debugging; please comment out again before PR.

env:
  TARGET_REGISTRY_KEY: ${{ github.event.inputs.transformation_environment == 'true' && 'TRAN' || 'MAIN' }}

concurrency:
  group: ci-${{ github.ref }}-${{ github.event.inputs.build_for_repository || '(n/a)' }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    outputs:
      lifecycle_name: ${{ steps.prepare.outputs.lifecycle_name }}
      environment: ${{ steps.prepare.outputs.environment }}
      registry_key: ${{ steps.prepare.outputs.registry_key }}
      registry: ${{ steps.prepare.outputs.registry }}
      acr_secret_prefix: ${{ steps.prepare.outputs.acr_secret_prefix }}
      check_powershell: ${{ steps.prepare.outputs.check_powershell }}
      check_dotnet: ${{ steps.prepare.outputs.check_dotnet }}
      check_docs_templates: ${{ steps.prepare.outputs.check_docs_templates }}
      build_docker_images: ${{ steps.prepare.outputs.docker_images }}
      publish_dotnet_packages: ${{ steps.prepare.outputs.publish_dotnet_packages }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine which checks need to run
        id: prepare
        run: |
          $lifecycleName = ./scripts/workflows/Resolve-LifecycleParameter `
              -Implied '${{ github.event_name == 'merge_group' && 'rel' || 'dev' }}' `
              -Override '${{ github.event.inputs.lifecycle }}'
          echo "lifecycle_name=$lifecycleName" >> $env:GITHUB_OUTPUT

          $environment = $lifecycleName -ceq 'rel' ? 'Release Lifecycle' : 'Development Lifecycle'
          echo "environment=$environment" >> $env:GITHUB_OUTPUT

          Write-Host "Using environment '$environment'."

          # Determine which registry to use 'MAIN' or 'TRAN'?
          $registryKey = '${{ env.TARGET_REGISTRY_KEY }}'
          echo "registry_key=$registryKey" >> $env:GITHUB_OUTPUT
          $registry = '${{ vars[format('ACR_REGISTRY_{0}', env.TARGET_REGISTRY_KEY)] }}'
          echo "registry=$registry" >> $env:GITHUB_OUTPUT

          # Determine secret prefix 'ACR_(TRAN|MAIN)_(DEV|REL)'.
          $acrSecretPrefix = "ACR_${{ env.TARGET_REGISTRY_KEY }}"
          echo "acr_secret_prefix=$acrSecretPrefix" >> $env:GITHUB_OUTPUT

          $changedFiles = ./scripts/workflows/Get-ChangedFilesInBranch

          ./scripts/workflows/Set-RequirementsOutput `
            -LifecycleName $lifecycleName `
            -ChangedFiles $changedFiles `
            -ForceCheckPowershell '${{ github.event.inputs.check_powershell || false }}' `
            -ForceCheckDotnet '${{ github.event.inputs.check_dotnet || false }}' `
            -ForceCheckDocs '${{ github.event.inputs.check_docs || false }}' `
            -BuildChangedProjects $($env:GITHUB_EVENT_NAME -ne 'workflow_dispatch') `
            -BuildForRepository '${{ github.event.inputs.build_for_repository || '(n/a)' }}' `
            -ForcePublishDotnetPackages '${{ github.event.inputs.publish_dotnet_packages || false }}'

  # -------------------------------------------------------------------------------------
  # Run checks, build and then publish any Docker images to the container registry.
  # -------------------------------------------------------------------------------------

  powershell-checks:
    name: Powershell checks
    uses: ./.github/workflows/powershell-checks.yml
    needs: prepare
    if: "${{ needs.prepare.outputs.check_powershell == 'true' }}"
    permissions:
      checks: write # Needed by 'dorny/test-reporter'.
      security-events: write # Needed by 'github/codeql-action/upload-sarif'.

  dotnet-checks:
    name: .NET checks
    uses: ./.github/workflows/dotnet-checks.yml
    needs: prepare
    if: "${{ needs.prepare.outputs.check_dotnet == 'true' }}"
    permissions:
      checks: write # Needed by 'dorny/test-reporter'.
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docs-templates-checks:
    name: Docs templates checks
    uses: ./.github/workflows/docs-templates-checks.yml
    needs: prepare
    if: "${{ needs.prepare.outputs.check_docs_templates == 'true' }}"
    permissions:
      checks: write # Needed by 'dorny/test-reporter'.

  image-build:
    name: Build docker images
    uses: ./.github/workflows/image-build.yml
    needs: prepare
    if: ${{ needs.prepare.outputs.build_docker_images != '[]' }}
    strategy:
      matrix:
        image: ${{ fromJson(needs.prepare.outputs.build_docker_images) }}
    secrets:
      ACR_MAIN_CLIENT_ID: ${{ secrets.ACR_MAIN_CLIENT_ID }}
      ACR_MAIN_CLIENT_SECRET: ${{ secrets.ACR_MAIN_CLIENT_SECRET }}
      ACR_TRAN_CLIENT_ID: ${{ secrets.ACR_TRAN_CLIENT_ID }}
      ACR_TRAN_CLIENT_SECRET: ${{ secrets.ACR_TRAN_CLIENT_SECRET }}
    with:
      environment: ${{ needs.prepare.outputs.environment }}
      project_name: ${{ matrix.image.project }}
      dockerfile: ${{ matrix.image.dockerfile }}
      version: ${{ matrix.image.version }}
      registry_key: ${{ needs.prepare.outputs.registry_key }}
      registry: ${{ needs.prepare.outputs.registry }}
      repository_name: ${{ matrix.image.repository }}
      tag_name: ${{ github.run_id }}

  dotnet-packages:
    name: .NET publish packages
    uses: ./.github/workflows/dotnet-packages.yml
    needs: prepare
    if: "${{ needs.prepare.outputs.publish_dotnet_packages == 'true' }}"
    permissions:
      id-token: write # Needed by 'azure/login'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    with:
      nuget_source: ${{ vars.AZURE_DEVOPS_NUGET_SOURCE }}

  # -------------------------------------------------------------------------------------
  # Publish any packages and trigger any CD pipelines.
  # -------------------------------------------------------------------------------------

  checks-passed:
    name: Checks passed
    runs-on: ubuntu-latest
    needs:
      - prepare
      - powershell-checks
      - dotnet-checks
      - image-build
      - dotnet-packages
      - docs-templates-checks
    if: ${{ always() }}
    steps:
      - name: Triggering deployments
        shell: pwsh
        run: |
          $statuses = @(
            '${{ needs.prepare.result }}'
            '${{ needs.powershell-checks.result }}'
            '${{ needs.dotnet-checks.result }}'
            '${{ needs.image-build.result }}'
            '${{ needs.dotnet-packages.result }}'
            '${{ needs.docs-templates-checks.result }}'
          )

          if ($statuses.Contains('failure') -or $statuses.Contains('cancelled')) {
            exit 1
          }

          Write-Host Triggering deployments...

  trigger-cd:
    name: Deploy
    uses: ./.github/workflows/image-deploy.yml
    needs: [prepare, checks-passed]
    if: ${{ !cancelled() && !failure() && needs.prepare.outputs.build_docker_images != '[]' }}
    strategy:
      fail-fast: false # Continue with other triggers even when some deployment triggers fail.
      matrix:
        image: ${{ fromJson(needs.prepare.outputs.build_docker_images) }}
    permissions:
      id-token: write # Needed by 'azure/login'
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    with:
      azure_pipeline_id: ${{ vars.AZURE_PIPELINE_ID_DEPLOY }}
      project_name: ${{ matrix.image.project }}
      repository_name: ${{ matrix.image.repository }}
      tag_name: ${{ github.run_id }}
      transformation_environment: ${{ needs.prepare.outputs.registry_key == 'TRAN' }}

  cleanup:
    name: Cleanup
    uses: ./.github/workflows/cleanup-deployments.yml
    needs: [prepare, checks-passed]
    if: ${{ always() }}
    permissions:
      deployments: write
