name: Deploy developer reference

on:
  workflow_call:

  # workflow_dispatch:
  #   inputs:
  #     override_lifecycle:
  #       description: 'Lifecycle (override)'
  #       required: false
  #       type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v3

      - name: Deploy image for developer reference docs
        shell: pwsh
        run: |
          Write-Host "Deploying image..."
