name: Build developer reference

on:
  workflow_call:
    inputs:
      project_name:
        description: Project name
        required: true
        type: string
        # options:
        #   - docs/external
        #   - docs/internal

      registry:
        description: Container registry
        required: true
        type: string

      repository_name:
        description: Container repository name
        required: true
        type: string

      tag_name:
        description: Image name
        required: true
        type: string

    secrets:
      ACR_CLIENT_ID:
        required: true
      ACR_CLIENT_SECRET:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.ACR_CLIENT_ID }}
          password: ${{ secrets.ACR_CLIENT_SECRET }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/docs/Dockerfile
          platforms: linux/amd64
          outputs: type=docker
          load: true
          build-args: |
            PROJECT_NAME=${{ inputs.project_name }}
          tags: '${{ inputs.registry }}/${{ inputs.repository_name }}:${{ inputs.tag_name }}'
          push: true
