name: Build developer reference

on:
  workflow_call:
    inputs:
      image_name:
        description: Image name
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET Core 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore .NET tools
        run: dotnet tool restore

      - name: Build custom template
        run: ./scripts/docs/Build-CustomTemplate

      - name: Build documentation
        run: ./scripts/workflows/Build-Docs -Audience 'External'

      - name: Build image
        run: |
          ./scripts/workflows/Build-StaticSiteImage `
            -RegistryServer 'fake' `
            -RepositoryName 'developer' `
            -ImageName '${{ inputs.image_name }}' `
            -HtmlPath 'docs/_site'
