name: Build image for .NET project

on:
  workflow_call:
    inputs:
      project_name:
        description: Project name
        required: true
        type: string

      image_name:
        description: Image name
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build image for '${{ inputs.project_name }}'
        run: |
          ./scripts/workflows/Build-DotNetImage `
            -RegistryServer 'fake' `
            -DotNetProjectName '${{ inputs.project_name }}' `
            -ImageName '${{ inputs.image_name }}'
