name: Publish development .NET packages

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Build project
        run: |
          dotnet build ./solutions/dsi-packages.sln `
            /p:Configuration=Release `
            /p:BuildPackages=true

      # - name: Authenticate to Azure
      #   uses: azure/login@v1
      #   with:
      #     client-id: ${{ secrets.AZURE_CLIENT_ID }}
      #     tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      #     subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # - name: Push NuGet package to Azure Artifacts
      #   run: |
      #     dotnet nuget push /**/*.nupkg `
      #       --source ${{ secrets.NUGET_SOURCE }} `
      #       --api-key ${{ secrets.AZURE_DEVOPS_TOKEN }} `
      #       --skip-duplicate
