name: Check .NET sources

on:
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Initialize solution for all projects
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: Copy-Item -Path ./dsi-platform.sln -Destination ./build.sln

      - name: Initialize solution for affected projects
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: ./scripts/workflows/Initialize-BuildSolutionForChangedProjects

      - name: Start sonar scanner
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin `
            /o:"dfe-digital" `
            /k:"DFE-Digital_dsi-platform" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: Build project
        run: dotnet build ./build.sln --no-incremental

      - name: Run unit tests
        run: |
          dotnet test ./build.sln `
            --collect "Code Coverage" `
            --logger "trx;LogFileName=TestResults.trx"

      - name: Report unit test results
        uses: dorny/test-reporter@v2.1.0
        if: ${{ !cancelled() }}
        with:
          name: .NET unit test results
          path: '**/*.trx'
          reporter: dotnet-trx

      - name: Stop sonar scanner
        run: |
          dotnet sonarscanner end `
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
