name: Publish development .NET packages

on:
  workflow_call:
    inputs:
      lifecycle_stage:
        description: The lifecycle_stage either 'dev' or 'rel'
        required: true
        type: string
    secrets:
      AZURE_DEVOPS_TOKEN:
        required: true
      AZURE_NUGET_SOURCE:
        required: true
      AZURE_NUGET_PROMOTION_SOURCE:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Build project
        run: |
          dotnet build ./solutions/dsi-packages.sln `
            /p:Configuration=Release `
            /p:BuildPackages=true

      - name: Push NuGet packages to Azure Artifacts
        run: |
          dotnet nuget add source "${{ secrets.AZURE_NUGET_SOURCE }}" `
            --name AzureArtifacts `
            --username "any" `
            --password "${{ secrets.AZURE_DEVOPS_TOKEN }}" `
            --store-password-in-clear-text

          Get-ChildItem -Path "$env:GITHUB_WORKSPACE/src" -Recurse -Filter "*.nupkg" |
            ForEach-Object {
              dotnet nuget push $_.FullName `
                --source AzureArtifacts `
                --api-key "${{ secrets.AZURE_DEVOPS_TOKEN }}" `
                --skip-duplicate
            }

      - name: Promote packages
        run: |
          Get-ChildItem -Path "$env:GITHUB_WORKSPACE/src" -Recurse -Filter "*.nupkg" |
            ForEach-Object {
              ./scripts/workflows/Promote-NuGetPackage.ps1 `
                  -PackagePath $_.FullName `
                  -LifecycleStage "${{ inputs.lifecycle_stage }}" `
                  -BaseFeedUrl "${{ secrets.AZURE_NUGET_PROMOTION_SOURCE }}" `
                  -Pat "${{ secrets.AZURE_DEVOPS_TOKEN }}"
            }
