name: Deploy image for .NET project

on:
  workflow_call:
    inputs:
      project_name:
        description: 'Project name'
        required: true
        type: string

      implied_lifecycle:
        description: 'Lifecycle (implied)'
        required: true
        type: string

      override_lifecycle:
        description: 'Lifecycle (override)'
        required: false
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v3

      - name: Deploy image for '${{ inputs.project_name }}'
        shell: pwsh
        run: |
          Write-Host "Deploying image..."
