name: Build image for .NET project

on:
  workflow_call:
    inputs:
      project_name:
        description: 'Project name'
        required: true
        type: string

      implied_lifecycle:
        description: 'Lifecycle (implied)'
        required: true
        type: string

      override_lifecycle:
        description: 'Lifecycle (override)'
        required: false
        type: string

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build image for '${{ inputs.project_name }}'
        shell: pwsh
        run: |
          Write-Host "Implied lifecycle '${{ inputs.implied_lifecycle }}'..."
          Write-Host "Override lifecycle '${{ inputs.override_lifecycle }}'..."

          if (-not '${{ inputs.override_lifecycle }}') {
            $lifecycle = '${{ inputs.override_lifecycle }}'.ToLower().Substring(0, 3)
          }
          else {
            $lifecycle = '${{ inputs.implied_lifecycle }}'
          }

          Write-Host "Using lifecycle '$lifecycle'..."

          ./scripts/actions/Build-DotNetImage `
            -RegistryServer 'fake' `
            -Lifecycle $lifecycle `
            -RunId '${{ github.run_id }}' `
            -RunNumber '${{ github.run_number }}' `
            -DotNetProjectName '${{ inputs.project_name }}'
