name: Build image for .NET project

on:
  workflow_call:
    inputs:
      project_name:
        description: Project name
        required: true
        type: string

      lifecycle_name:
        description: Lifecycle name
        required: true
        type: string
        # options:
        #   - dev
        #   - rel

      image_name:
        description: Image name
        required: true
        type: string

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare
        id: prepare
        run: |
          $repositoryName = ./scripts/workflows/Get-RepositoryForProjectName `
            -ProjectName '${{ inputs.project_name }}' `
            -LifecycleName '${{ inputs.lifecycle_name }}'
          Write-Host "Repository name: $repositoryName"
          echo "repository_name=$repositoryName" >> $env:GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # - name: Log in to Azure Container Registry
      #   uses: docker/login-action@v3
      #   with:
      #     registry: <registry-name>.azurecr.io
      #     username: ${{ secrets.AZ_SP_CLIENT_ID }}
      #     password: ${{ secrets.AZ_SP_CLIENT_SECRET }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          file: ./docker/dotnet-component/Dockerfile
          build-args: |
            PROJECT_NAME=${{ inputs.project_name }}
          tags: 'fake/${{ steps.prepare.outputs.repository_name }}:${{ inputs.image_name }}'
          push: false
