name: Publish development .NET packages

on:
  workflow_call:
    inputs:
      nuget_source:
        description: Nuget source URL
        required: true
        type: string

    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core 8.x
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.x"

      - name: Build project
        run: |
          dotnet build ./solutions/dsi-packages.sln `
            /p:Configuration=Release `
            /p:BuildPackages=true `
            /p:BuildDocs=true

      - name: Login to Azure
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true
          enable-AzPSSession: true

      - name: Get access token for Azure DevOps
        run: |
          $token = az account get-access-token `
            --resource 499b84ac-1321-427f-aa17-267ca6975798 `
            --query "accessToken" -o tsv
          echo "AZURE_DEVOPS_TOKEN=$token" >> $env:GITHUB_ENV

      - name: Push NuGet package to Azure Artifacts
        run: |
          dotnet nuget add source "${{ inputs.nuget_source }}" `
            --name AzureArtifacts `
            --username "any" `
            --password "$env:AZURE_DEVOPS_TOKEN" `
            --store-password-in-clear-text

          Get-ChildItem -Path ./packages -Filter *.nupkg | ForEach-Object {
            dotnet nuget push $_.FullName `
              --source AzureArtifacts `
              --api-key null `
              --skip-duplicate
          }
