name: Build docker image

on:
  workflow_call:
    inputs:
      environment:
        description: Environment name
        required: true
        type: string

      project_name:
        description: Project name
        required: true
        type: string

      dockerfile:
        description: Dockerfile name
        required: true
        type: string

      version:
        description: Version
        required: false
        type: string
        default: "0.0.0"

      registry_key:
        description: Container registry key
        required: true
        type: string

      registry:
        description: Container registry
        required: true
        type: string

      repository_name:
        description: Container repository name
        required: true
        type: string

      tag_name:
        description: Image name
        required: true
        type: string

    secrets:
      ACR_MAIN_CLIENT_ID:
        required: true
      ACR_MAIN_CLIENT_SECRET:
        required: true
      ACR_TRAN_CLIENT_ID:
        required: true
      ACR_TRAN_CLIENT_SECRET:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435

      - name: Log in to Azure Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets[format('ACR_{0}_CLIENT_ID', inputs.registry_key)] }}
          password: ${{ secrets[format('ACR_{0}_CLIENT_SECRET', inputs.registry_key)] }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: ./docker/${{ inputs.dockerfile }}/Dockerfile
          platforms: linux/amd64
          outputs: type=image,push=true
          provenance: false
          build-args: |
            PROJECT_NAME=${{ inputs.project_name }}
          tags: "${{ inputs.registry }}/${{ inputs.repository_name }}:${{ inputs.tag_name }}"
          annotations: |
            uk.gov.education.signin.source=https://github.com/${{ github.repository }}
            uk.gov.education.signin.revision=${{ github.sha }}
            uk.gov.education.signin.run_id=${{ github.run_id }}
            uk.gov.education.signin.run_attempt=${{ github.run_attempt }}
            uk.gov.education.signin.version=${{ inputs.version }}
          labels: |
            org.opencontainers.image.title=${{ inputs.project_name }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.url=https://github.com/${{ github.repository }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            uk.gov.education.signin.run_id=${{ github.run_id }}
            uk.gov.education.signin.run_attempt=${{ github.run_attempt }}
          push: true
