name: Deploy image

on:
  workflow_call:
    inputs:
      project_name:
        description: Project name
        required: true
        type: string

      repository_name:
        description: Container repository name
        required: true
        type: string

      tag_name:
        description: Image name
        required: true
        type: string

      transformation_environment:
        description: For transformation environment
        required: true
        type: boolean

    secrets:
      AZURE_DEVOPS_TOKEN:
        required: true
      AZURE_DEVOPS_PROJECT:
        required: true
      AZURE_PIPELINE_ID:
        required: true

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    outputs:
      azure_pipeline_url: ${{ steps.prepare.outputs.azure_pipeline_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy image for '${{ inputs.project_name }}'
        id: prepare
        run: |
          $azurePipelineUrl = ./scripts/workflows/Initialize-AzurePipeline `
              -Pat "${{ secrets.AZURE_DEVOPS_TOKEN }}" `
              -OrgProjectUrl "${{ secrets.AZURE_DEVOPS_PROJECT }}" `
              -PipelineId "${{ secrets.AZURE_PIPELINE_ID }}" `
              -BranchRef "${{ vars.AZURE_DEVOPS_BRANCH }}" `
              -ProjectName "${{ inputs.project_name }}" `
              -RepositoryName "${{ inputs.repository_name }}" `
              -Tag "${{ inputs.tag_name }}" `
              -TransformationEnv $True
          Write-Host "Azure Pipeline URL: $azurePipelineUrl"
          Add-Content -Path $env:GITHUB_OUTPUT -Value "azure_pipeline_url=$azurePipelineUrl"
