name: Deploy image

on:
  workflow_call:
    inputs:
      project_name:
        description: Project name
        required: true
        type: string

      repository_name:
        description: Container repository name
        required: true
        type: string

      tag_name:
        description: Concatenation of github.run_id and github.run_attempt
        required: true
        type: string

      transformation_environment:
        description: For transformation environment
        required: true
        type: boolean

      github_username:
        description: The github username that triggered the deployment
        required: true
        type: string

      github_title:
        description: The github pr or title
        required: true
        type: string

      github_workflow_url:
        description: Link to the github workflow
        required: true
        type: string

    secrets:
      AZURE_DEVOPS_TOKEN:
        required: true
      AZURE_DEVOPS_PROJECT:
        required: true
      AZURE_PIPELINE_ID:
        required: true
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy image for '${{ inputs.project_name }}'
        id: prepare
        run: |
          $azurePipelineResponse = ./scripts/workflows/Initialize-AzurePipeline `
              -Pat "${{ secrets.AZURE_DEVOPS_TOKEN }}" `
              -OrgProjectUrl "${{ secrets.AZURE_DEVOPS_PROJECT }}" `
              -PipelineId "${{ secrets.AZURE_PIPELINE_ID }}" `
              -BranchRef "${{ vars.AZURE_DEVOPS_BRANCH }}" `
              -ProjectName "${{ inputs.project_name }}" `
              -RepositoryName "${{ inputs.repository_name }}" `
              -Tag "${{ inputs.tag_name }}" `
              -TransformationEnv $True
          $pipelineUrl = $azurePipelineResponse._links.web.href
          echo "AZURE_PIPELINE_URL=$pipelineUrl" >> $env:GITHUB_ENV

      # slack notification is part of image-deploy because image-deploy runs a matrix which won't return
      # an output that can be collected and used by a downstream job.  Therefore, for each run of image
      # capture the required properties and issue the notification.
      - name: Generate slack notification
        run: |
          $targetEnv = "${{ startsWith(inputs.repository_name, 'dev/') && 'DEV' || 'PREPROD' }}"
          $subMessage = "*${{ inputs.project_name }}* is ready to be deployed to $targetEnv by ${{ inputs.github_username }}"
          $mainMessage = "Branch: ${{ inputs.github_title }}`n<${{ inputs.github_workflow_url }}|Github workflow>`n<$env:AZURE_PIPELINE_URL|Azure pipeline>" `

          ./scripts/workflows/Send-SlackNotification `
              -SlackUri "${{ secrets.SLACK_WEBHOOK_URL }}" `
              -SlackMessageHeading ".NET Deployment" `
              -SlackSubMessage $subMessage `
              -SlackMainMessage $mainMessage
