name: Check PowerShell scripts

on:
  workflow_call:

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run code quality tests
        uses: microsoft/psscriptanalyzer-action@v1.1
        with:
          path: ./scripts
          recurse: true
          enableExit: true
          severity: '"Error", "Warning"'
          settings: ./.config/PSScriptAnalyzerSettings.psd1
          output: powershell-checks.sarif

      - name: Upload code quality results
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ !cancelled() }}
        with:
          sarif_file: powershell-checks.sarif
          category: powershell-checks

      - name: Run unit tests
        if: ${{ !cancelled() }}
        run: |
          Invoke-Pester -Configuration $(New-PesterConfiguration -Hashtable $(
            Import-PowerShellDataFile ./.config/PesterSettings.psd1
          ))

      - name: Report unit test results
        uses: dorny/test-reporter@v2.1.0
        if: ${{ !cancelled() }}
        with:
          name: Powershell unit test results
          path: ./scripts/TestResults.xml
          reporter: jest-junit

      - name: Summarise code coverage
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: ${{ !cancelled() }}
        with:
          filename: ./scripts/Coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '80 80'

      - name: Report code coverage
        if: ${{ !cancelled() }}
        run: |
          $content = Get-Content code-coverage-results.md
          Add-Content -Path $env:GITHUB_STEP_SUMMARY -Value $content
