name: Check PowerShell scripts

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run unit tests
        run: Invoke-Pester ./scripts/**/*.Tests.ps1 -Passthru | Export-JUnitReport -Path ./scripts/TestResults.xml

      - name: Report unit test results
        uses: dorny/test-reporter@v2.1.0
        if: ${{ !cancelled() }}
        with:
          name: Powershell unit test results
          path: ./scripts/TestResults.xml
          reporter: jest-junit
