parameters:
  - name: buildSelectOrganisation
    type: boolean
    displayName: "Build 'Select Organisation'"
    default: false
  - name: buildPublicApi
    type: boolean
    displayName: "Build 'Public API'"
    default: false

  - name: lifecycle
    type: string
    displayName: Lifecycle
    default: Development
    values:
      - Development
      - Release

  - name: containerRegistry
    type: string
    displayName: Container registry
    default: D03
    values:
      - Standard
      - D03

  - name: applications
    type: object
    default:
      - displayName: Select Organisation
        name: select-organisation
        shortName: sltOrg
        projectName: Dfe.SignIn.Web.SelectOrganisation
        triggerVariable: buildSelectOrganisation

      - displayName: Public API
        name: public-api-v2
        shortName: papiV2
        projectName: Dfe.SignIn.PublicApi
        triggerVariable: buildPublicApi

jobs:
  - ${{ each application in parameters.applications }}:
    - job: buildImages_${{ application.shortName }}
      displayName: Build image for '${{ application.displayName }}'

      # For development lifecycle allow images to be deployed to the TRAN/DEV/TEST
      # environments with failing checks. Do not permit this for release lifecycles.
      ${{ if not(eq(parameters.lifecycle, 'Development')) }}:
        dependsOn: dotnetChecks

      pool:
        vmImage: ubuntu-latest

      variables:
        - name: containerRegistryServer
          ${{ if eq( parameters.containerRegistry, 'Standard') }}:
            value: "$(platformGlobalIdentifier)$(prShaCode)$(platformGlobalName)shdcr.azurecr.io"
          ${{ if eq( parameters.containerRegistry, 'D03') }}:
            value: "$(platformGlobalIdentifier)$(tranShaCode)$(platformGlobalName)shdcr.azurecr.io"

      steps:
        - checkout: self
          persistCredentials: true
          path: s/self
        - checkout: devopsTemplates
          path: s/devopsTemplates

        - task: PowerShell@2
          displayName: Verify container registry for lifecycle
          inputs:
            filePath: '$(System.DefaultWorkingDirectory)/self/scripts/pipelines/Test-LifecycleContainerRegistry.ps1'
            workingDirectory: '$(System.DefaultWorkingDirectory)/self'
            arguments: >
              -Lifecycle "${{ parameters.lifecycle }}"
              -ContainerRegistry "${{ parameters.containerRegistry }}"

        - template: ./dotnet-select-projects.yml

        - task: PowerShell@2
          displayName: Check needs building
          inputs:
            targetType: inline
            script: |
              if (
                '$(deployProjectNames)' -like '**${{ application.projectName }};**' -or
                '${{ parameters[application.triggerVariable] }}' -eq 'true'
              ) {
                Write-Host "##vso[task.setvariable variable=buildImage]true"
              }

        - task: CopyFiles@2
          displayName: "Copy Docker files"
          condition: and(succeeded(), eq(variables.buildImage, 'true'))
          inputs:
            SourceFolder: $(System.DefaultWorkingDirectory)/devopsTemplates
            Contents: |
              docker/Linux-app-service/**
            TargetFolder: $(System.DefaultWorkingDirectory)/Publish
            CleanTargetFolder: true
        
        - task: CopyFiles@2
          displayName: "Copy Docker files"
          condition: and(succeeded(), eq(variables.buildImage, 'true'))
          inputs:
            SourceFolder: $(System.DefaultWorkingDirectory)/self
            Contents: |
              **
            TargetFolder: $(System.DefaultWorkingDirectory)/Publish
            CleanTargetFolder: false

        - task: AzureCLI@2
          displayName: Build image for '${{ application.displayName }}'
          condition: and(succeeded(), eq(variables.buildImage, 'true'))
          inputs:
            azureSubscription: $(devServiceConnection)
            scriptType: pscore
            scriptLocation: scriptPath
            scriptPath: $(System.DefaultWorkingDirectory)/self/scripts/pipelines/Build-Image.ps1
            arguments: >
              -RegServer "$(containerRegistryServer)"
              -AppName "${{ application.name }}"
              -Lifecycle "${{ parameters.lifecycle }}"
              -BuildId $(Build.BuildId)
              -DockerFileName "appSvcDotNet"
              -DotNetProjName "${{ application.projectName }}"
            workingDirectory: $(System.DefaultWorkingDirectory)/Publish
