name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)

resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/login.dfe.devops
      ref: feature/DSI-7357

trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - src/*
      - tests/*

parameters:
  - name: buildSelectOrganisation
    type: boolean
    displayName: "Build 'Select Organisation'"
    default: false
  - name: buildPublicApi
    type: boolean
    displayName: "Build 'Public API'"
    default: false
  - name: publishAllPackages
    type: boolean
    displayName: "Publish all packages"
    default: false

  - name: target
    type: string
    displayName: Target
    default: Development
    values:
      - Development
      - Release
  - name: forTranEnvironment
    type: boolean
    displayName: "For TRAN environment"
    default: true

variables:
  - group: dsi-global
  - group: dsi-envs-list

jobs:
  - template: ./templates/dotnet-checks.yml
    parameters:
      publishAllPackages: ${{ parameters.publishAllPackages }}

  - template: ./templates/dotnet-build-images.yml
    parameters:
      buildSelectOrganisation: ${{ parameters.buildSelectOrganisation }}
      buildPublicApi: ${{ parameters.buildPublicApi }}
      target: ${{ parameters.target }}
      forTranEnvironment: ${{ parameters.forTranEnvironment }}
